databases:
  - name: ecommerce-shopkart
    databaseName: TEMPLATEAPP_DATABASE
    user: postgres

services:
  - type: web
    name: ecommerce-shopkart
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TEMPLATEAPP_DATABASE
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false 